title: Fanjie Zeng's Homepage
page-top-title: Fanjie Zeng
top-section-bg-text: Power Engineering
home-subtitle: Fanjie Zeng&ensp;|&ensp;曾凡杰
copyright-text: '&copy; Fanjie Zeng 2024-2025. All Rights Reserved.'
